# Generated by Django 5.1.5 on 2025-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_and_zayavka", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymethod",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="delivery_logos/"),
        ),
    ]
