# Generated by Django 5.1.5 on 2025-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_and_zayavka", "0003_deliveryprice_district_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuppoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
