# Generated by Django 5.1.5 on 2025-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_and_zayavka",
            "0004_pickuppoint_latitude_pickuppoint_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="address",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="address_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="zayafka",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
