# Generated by Django 5.1.5 on 2025-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_and_zayavka",
            "0005_alter_deliveryaddress_address_alter_district_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
