# Generated by Django 5.1.5 on 2025-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="news_images/")),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("faol", "Faol"),
                            ("faol_emas", "Faol emas"),
                            ("yangi", "Yangi"),
                            ("rasprodaja", "Rasprodaja"),
                        ],
                        default="yangi",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("images", models.ManyToManyField(blank=True, to="News.image")),
            ],
        ),
    ]
