# Generated by Django 5.1.5 on 2025-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
