# Generated by Django 5.1.5 on 2025-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
