# Generated by Django 5.1.5 on 2025-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_uz", models.CharField(blank=True, max_length=255, null=True)),
                ("key_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("value_uz", models.CharField(blank=True, max_length=255, null=True)),
                ("value_ru", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
