# Generated by Django 5.1.5 on 2025-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="images",
            field=models.ManyToManyField(blank=True, to="Service.serviceimage"),
        ),
    ]
