# Generated by Django 5.1.5 on 2025-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Service", "0002_service_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
