# Generated by Django 5.1.5 on 2025-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Service", "0003_alter_service_description_uz_alter_service_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("faol", "Faol"),
                    ("faol_emas", "Faol emas"),
                    ("yangi", "Yangi"),
                    ("sotilgan", "Sotilgan"),
                ],
                default="faol",
                max_length=20,
            ),
        ),
    ]
