# Generated by Django 5.1.5 on 2025-02-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesktopAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_uz", models.CharField(max_length=255)),
                ("key_ru", models.CharField(max_length=255)),
                ("value_uz", models.TextField()),
                ("value_ru", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DesktopType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="desktop_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Desktop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("faol", "Faol"),
                            ("faol_emas", "Faol emas"),
                            ("yangi", "Yangi"),
                            ("rasprodaja", "Rasprodaja"),
                        ],
                        default="yangi",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="desktops",
                        to="DesktopFPSGames.desktopattributes",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desktops",
                        to="DesktopFPSGames.desktoptype",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(blank=True, to="DesktopFPSGames.image"),
                ),
            ],
        ),
    ]
