# Generated by Django 5.1.5 on 2025-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desktopattributes",
            name="value_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="desktopattributes",
            name="value_uz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
