# Generated by Django 5.1.5 on 2025-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0002_alter_desktopattributes_value_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desktoptype",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
