# Generated by Django 5.1.5 on 2025-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0003_alter_desktoptype_name_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="desktopattributes",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="desktopattributes",
            name="key_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
