# Generated by Django 5.1.5 on 2025-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0004_desktopattributes_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desktop",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
