# Generated by Django 5.1.5 on 2025-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0005_alter_desktop_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desktop",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
