# Generated by Django 5.1.5 on 2025-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0006_alter_desktop_description_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desktopattributes",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
