# Generated by Django 5.1.5 on 2025-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DesktopFPSGames", "0007_alter_desktopattributes_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desktop",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="desktopattributes",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="desktoptype",
            name="slug",
        ),
        migrations.AlterField(
            model_name="desktop",
            name="status",
            field=models.CharField(
                choices=[
                    ("faol", "Faol"),
                    ("faol_emas", "Faol emas"),
                    ("yangi", "Yangi"),
                    ("sotilgan", "Sotilgan"),
                ],
                default="yangi",
                max_length=20,
            ),
        ),
    ]
