# Generated by Django 5.1.5 on 2025-02-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
