# Generated by Django 5.1.5 on 2025-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0002_alter_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
