# Generated by Django 5.1.5 on 2025-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0003_alter_banner_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
