# Generated by Django 5.1.5 on 2025-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0004_alter_banner_description_uz_alter_banner_name_uz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
