# Generated by Django 5.1.5 on 2025-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0005_alter_banner_description_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
