# Generated by Django 5.1.5 on 2025-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banner", "0006_alter_banner_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="status",
            field=models.CharField(
                choices=[
                    ("faol", "Faol"),
                    ("faol_emas", "Faol emas"),
                    ("yangi", "Yangi"),
                    ("sotilgan", "Sotilgan"),
                ],
                default="faol",
                max_length=50,
            ),
        ),
    ]
