# Generated by Django 5.1.5 on 2025-02-02 18:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_uz",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="slug",
            field=models.SlugField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        ),
    ]
