# Generated by Django 5.1.5 on 2025-02-02 22:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_type_name_ru_alter_type_name_uz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="slug",
            field=models.SlugField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
