# Generated by Django 5.1.5 on 2025-02-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("faol", "Faol"),
                    ("faol_emas", "Faol emas"),
                    ("yangi", "Yangi"),
                    ("rasprodaja", "Rasprodaja"),
                    ("discounted", "Chegirma"),
                ],
                default="faol",
                max_length=20,
            ),
        ),
    ]
