# Generated by Django 5.1.5 on 2025-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="som_value",
            field=models.DecimalField(decimal_places=2, default=12000, max_digits=5),
        ),
    ]
