# Generated by Django 5.1.5 on 2025-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_conversion_som_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="som_value",
            field=models.DecimalField(decimal_places=2, default=12000, max_digits=7),
        ),
    ]
