# Generated by Django 5.1.5 on 2025-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_conversion_som_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="key",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="value",
        ),
        migrations.AddField(
            model_name="attribute",
            name="key_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attribute",
            name="key_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attribute",
            name="value_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attribute",
            name="value_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
