# Generated by Django 5.1.5 on 2025-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_attribute_key_remove_attribute_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="type",
            name="slug",
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
