# Generated by Django 5.1.5 on 2025-02-12 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_category_slug_remove_type_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="slug",
        ),
    ]
