# Generated by Django 5.1.5 on 2025-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
