# Generated by Django 5.1.5 on 2025-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_brand_name_alter_category_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
