# Generated by Django 5.1.5 on 2025-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_description_uz_alter_product_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("faol", "Faol"),
                    ("faol_emas", "Faol emas"),
                    ("yangi", "Yangi"),
                    ("sotilgan", "Sotilgan"),
                    ("discounted", "Chegirma"),
                ],
                default="faol",
                max_length=20,
            ),
        ),
    ]
